# services/llm_service.py
from openai import OpenAI
from config.settings import OPENAI_API_KEY
from prompts.templates import build_rag_prompt
from app_logging.logger import get_logger

# Use your perfectly centralized logger
logger = get_logger("LLM_Service")
openai_client = OpenAI(api_key=OPENAI_API_KEY)

def generate_response(user_query: str, search_results: list) -> str:
    """
    Constructs the prompt and sends it to OpenAI for generation.
    """
    system_prompt, user_prompt = build_rag_prompt(user_query, search_results)
    
    try:
        response = openai_client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3
        )
        return response.choices[0].message.content or "No response generated by the AI."
    except Exception as e:
        logger.error(f"Failed to generate response: {e}")
        return f"An error occurred while communicating with the AI: {e}"