# services/llm_service.py
import time
import json
from typing import Tuple
from openai import OpenAI, OpenAIError
from config.settings import OPENAI_API_KEY
from prompts.templates import build_rag_prompt
from app_logging.logger import get_logger

logger = get_logger("LLM_Service")
openai_client = OpenAI(api_key=OPENAI_API_KEY)

def generate_response(user_query: str, search_results: list) -> Tuple[str, float, int]:
    """
    Constructs the prompt and sends it to OpenAI for generation.
    Returns the answer string, generation latency in ms, and token count.
    """
    start_time = time.perf_counter()
    system_prompt, user_prompt = build_rag_prompt(user_query, search_results)
    
    try:
        logger.info("Sending generation request to OpenAI API (gpt-3.5-turbo).")
        response = openai_client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3
        )
        
        answer = response.choices[0].message.content or "No response generated by the AI."
        generation_time = (time.perf_counter() - start_time) * 1000
        
        # Extract actual token usage from OpenAI response
        tokens_used = response.usage.total_tokens if response.usage else int(len(answer.split()) * 1.3)
        logger.info(f"OpenAI API response received in {generation_time:.2f} ms. Tokens used: {tokens_used}")
        
        return answer, generation_time, tokens_used
        
    except OpenAIError as e:
        # IMPROVEMENT: Specifically catch OpenAI API limits/timeouts
        logger.error(f"OpenAI API Error: {e}", exc_info=True)
        fallback_msg = "I am currently experiencing high latency or rate limits with the AI provider. Please try asking your question again in a moment."
        return fallback_msg, 0.0, 0
        
    except Exception as e:
        # IMPROVEMENT: Graceful degradation for the UI (hides raw backend errors from the user)
        logger.error(f"Unexpected error during LLM generation: {e}", exc_info=True)
        fallback_msg = "An unexpected error occurred while generating the response. My systems have logged the issue for review."
        return fallback_msg, 0.0, 0

def evaluate_response_quality(query: str, retrieved_context: str, generated_response: str) -> dict:
    """
    LLM-as-a-Judge implementation to systematically score the RAG generation pipeline
    across 6 core production metrics using structured JSON output.
    """
    logger.info("Initiating LLM-as-a-Judge response evaluation.")
    
    judge_prompt = f"""
    You are an expert enterprise AI evaluator grading a Retrieval-Augmented Generation (RAG) system.
    Analyze the original user query, the retrieved context chunks, and the generated system response carefully.
    
    Query: {query}
    Retrieved Context: {retrieved_context}
    Generated Response: {generated_response}
    
    Score the following criteria strictly from 1 to 5 (1 being poor/inaccurate, 5 being flawless/perfect):
    1. answer_relevance: Does the response directly, cleanly, and fully address the user's core intent?
    2. context_faithfulness: Is the response strictly grounded in the provided context? Deduct points for any outside assumptions or hallucinations.
    3. completeness: Does the response fully answer all explicit and implicit aspects of the user's question?
    4. correctness: Is the information factually accurate and completely true relative to the provided text?
    5. clarity: Is the structure, readability, and delivery of the text optimal and highly professional?
    6. source_citation_quality: Does the response properly and clearly credit the target context documentation without misattribution?
    
    Your output must be strictly formatted as a valid JSON object matching this exact schema:
    {{
        "answer_relevance": int,
        "context_faithfulness": int,
        "completeness": int,
        "correctness": int,
        "clarity": int,
        "source_citation_quality": int
    }}
    """
    
    try:
        response = openai_client.chat.completions.create(
            model="gpt-3.5-turbo",
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": "You are a rigid and objective JSON evaluation utility."},
                {"role": "user", "content": judge_prompt}
            ],
            temperature=0.0  # Zero temperature ensures consistent, deterministic evaluation grading
        )
        
        raw_content = response.choices[0].message.content or "{}"
        evaluation_result = json.loads(raw_content)
        logger.info("Successfully received structured validation scores from LLM judge.")
        return evaluation_result
        
    except Exception as e:
        logger.error(f"LLM-as-a-Judge evaluation failure: {e}", exc_info=True)
        # Safe fallback dictionary to ensure the evaluation engine script never crashes out mid-run
        return {
            "answer_relevance": 0,
            "context_faithfulness": 0,
            "completeness": 0,
            "correctness": 0,
            "clarity": 0,
            "source_citation_quality": 0
        }