# services/llm_service.py
import time
from typing import Tuple
from openai import OpenAI, OpenAIError
from config.settings import OPENAI_API_KEY
from prompts.templates import build_rag_prompt
from app_logging.logger import get_logger

logger = get_logger("LLM_Service")
openai_client = OpenAI(api_key=OPENAI_API_KEY)

def generate_response(user_query: str, search_results: list) -> Tuple[str, float, int]:
    """
    Constructs the prompt and sends it to OpenAI for generation.
    Returns the answer string, generation latency in ms, and token count.
    """
    start_time = time.perf_counter()
    system_prompt, user_prompt = build_rag_prompt(user_query, search_results)
    
    try:
        logger.info("Sending generation request to OpenAI API (gpt-3.5-turbo).")
        response = openai_client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3
        )
        
        answer = response.choices[0].message.content or "No response generated by the AI."
        generation_time = (time.perf_counter() - start_time) * 1000
        
        # Extract actual token usage from OpenAI response
        tokens_used = response.usage.total_tokens if response.usage else int(len(answer.split()) * 1.3)
        logger.info(f"OpenAI API response received in {generation_time:.2f} ms. Tokens used: {tokens_used}")
        
        return answer, generation_time, tokens_used
        
    except OpenAIError as e:
        # IMPROVEMENT: Specifically catch OpenAI API limits/timeouts
        logger.error(f"OpenAI API Error: {e}", exc_info=True)
        fallback_msg = "I am currently experiencing high latency or rate limits with the AI provider. Please try asking your question again in a moment."
        return fallback_msg, 0.0, 0
        
    except Exception as e:
        # IMPROVEMENT: Graceful degradation for the UI (hides raw backend errors from the user)
        logger.error(f"Unexpected error during LLM generation: {e}", exc_info=True)
        fallback_msg = "An unexpected error occurred while generating the response. My systems have logged the issue for review."
        return fallback_msg, 0.0, 0